[apps.aws.dev]
# Use env-select to load more secrets Ripped ~/git/portal/dev.sh api creds
# We may want to rip the code for DB creds here too (TBD)
JWT_SECRET_KEY = {command = "aws secretsmanager get-secret-value --secret-id arn:aws:secretsmanager:us-east-1:692674046581:secret:cp_jwt_secret_dev-eTk6oj | jq -r '.SecretString | fromjson | .dev_jwt_secret'"}
