#:schema https://docs.jj-vcs.dev/latest/config-schema.json

[user]
email = "lucas@lucaspickering.me"
name = "Lucas Pickering"

[aliases]
bk = ["bookmark"]
sq = ["squash"]

[revsets]
bookmark-advance-to = 'closest_pushable(@)'

[revset-aliases]
# Closest revision that is mutable, described and either non-empty or a merge
'closest_pushable(to)' = '''
  heads(::to & mutable() & ~description(exact:"") & (~empty() | merges()))
'''
