version: '3.7'

services:
  mc:
    image: itzg/minecraft-server
    environment:
      EULA: "true"
      TYPE: PURPUR
      # BUILD_FROM_SOURCE: "true"
      VERSION: "1.18.2"
      MEMORY: 10g
      ENABLE_ROLLING_LOGS: "true"
    # command: --noconsole
    ports:
      - 25565:25565
    volumes:
      - ./data:/data:rw
