[[language]]
name = "git-commit"
soft-wrap.enable = true
soft-wrap.wrap-at-text-width = true
soft-wrap.wrap-indicator = ""

[[language]]
file-types = ["gitconfig", {glob = "gitconfig"}]
name = "git-config"

[[language]]
file-types = ["ghostty", {glob = "ghostty/config"}]
name = "ghostty"

[[language]]
auto-format = true
formatter = {command = "dprint", args = ["fmt", "--stdin", "js"]}
language-servers = ["deno-lsp"]
name = "javascript"

[[language]]
language-servers = ["jinja-lsp"]
name = "jinja"

[language-server.jinja-lsp]
command = "jinja-lsp"
timeout = 5

[[language]]
auto-format = true
indent = {tab-width = 2, unit = "    "}
language-servers = ["kdl-lsp"]
name = "kdl"

[language-server.kdl-lsp]
command = "kdl-lsp"

[[language]]
auto-format = true
comment-tokens = ["-"] # Continue list on newline
formatter = {command = "dprint", args = ["fmt", "--stdin", "md"]}
name = "markdown"
soft-wrap.enable = true
soft-wrap.wrap-at-text-width = false
soft-wrap.wrap-indicator = ""

[[language]]
auto-format = true
language-servers = ["ty", "ruff"]
name = "python"
rulers = [88]

[language-server.ruff]
args = ["server"]
command = "ruff"

[language-server.rust-analyzer.config]
cargo.targetDir = true
check.command = "clippy"
imports.granularity = "crate"
imports.group.enable = false
imports.prefix = "crate"
inlayHints.closingBraceHints.enable = false
inlayHints.parameterHints.enable = false
inlayHints.typeHints.enable = false
references.excludeImports = true
references.excludeTests = true
rustfmt.extraArgs = ["+nightly"]
workspace.symbol.search.excludeImports = true

[[language]]
auto-format = true
formatter = {command = "taplo", args = [
  "format",
  "-o=align_comments=false",
  "-o=array_auto_expand=false",
  "-o=array_auto_collapse=false",
  "-o=compact_inline_tables=true",
  "-o=reorder_keys=true",
  "-",
]}
name = "toml"

[[language]]
auto-format = true
formatter = {command = "dprint", args = ["fmt", "--stdin", "ts"]}
language-servers = ["deno-lsp"]
name = "tsx"

[[language]]
auto-format = true
formatter = {command = "dprint", args = ["fmt", "--stdin", "ts"]}
language-servers = ["deno-lsp"]
name = "typescript"

[language-server.deno-lsp]
args = ["lsp"]
command = "deno"

[language-server.deno-lsp.config.deno]
enable = true

[language-server.tinymist.config]
preview.background.args = [
  "--data-plane-host=127.0.0.1:0",
  "--invert-colors=never",
  "--open",
]
preview.background.enabled = true
