[[language]]
name = "git-commit"
soft-wrap.enable = true
soft-wrap.wrap-at-text-width = true
soft-wrap.wrap-indicator = ""

[[language]]
name = "git-config"
file-types = ["gitconfig", {glob = "gitconfig"}]

[[language]]
name = "ghostty"
file-types = ["ghostty", {glob = "ghostty/config"}]

[[language]]
name = "markdown"
comment-tokens = ["-"] # Continue list on newline
formatter = {command = "dprint", args = ["fmt", "--stdin", "md"]}
auto-format = true
soft-wrap.enable = true
soft-wrap.wrap-at-text-width = false
soft-wrap.wrap-indicator = ""

[[language]]
name = "python"
language-servers = ["ruff", "ty"]
rulers = [88]
auto-format = true

[language-server.ruff]
command = "ruff"
args = ["server"]

[[language]]
name = "rust"
rulers = [81]

[language-server.rust-analyzer.config]
cargo.targetDir = true
check.command = "clippy"
imports.prefix = "crate"
imports.group.enable = false
imports.granularity = "crate"
inlayHints.closingBraceHints.enable = false
inlayHints.parameterHints.enable = false
inlayHints.typeHints.enable = false
rustfmt.extraArgs = ["+nightly"]
workspace.symbol.search.excludeImports = true
references.excludeImports = true
references.excludeTests = true
