version: "3"

volumes:
  transmission-torrents:

services:
  # https://github.com/dperson/openvpn-client/blob/master/docker-compose.yml
  vpn:
    image: dperson/openvpn-client
    restart: unless-stopped
    command: -f ""
    tty: true
    stdin_open: true
    # if using '-d' or 'DNS' you can't enable the `read_only: true` option
    read_only: true
    environment:
      VPN_AUTH:
    cap_add:
      - net_admin
    dns:
      - 1.1.1.1
    tmpfs:
      - /run
      - /tmp
    security_opt:
      - label:disable
    volumes:
      - /dev/net:/dev/net:z
      - ./vpn:/vpn

  proxy:
    image: dperson/nginx
    restart: unless-stopped
    command: -w "http://transmission:9091;/transmission"
    depends_on:
      - transmission
    links:
      - vpn:transmission
    ports:
      - "80:80"
      - "443:443"
    read_only: true
    tmpfs:
      - /run
      - /tmp
      - /var/cache/nginx

  transmission:
    build: ./transmission
    restart: unless-stopped
    network_mode: "service:vpn"
    depends_on:
      - vpn
    volumes:
      - /media/Torrents:/var/torrents:rw
      - transmission-torrents:/root/.config/transmission-daemon/torrents:rw

  plex:
    image: linuxserver/plex
    restart: unless-stopped
    network_mode: host
    environment:
      VERSION: docker
    volumes:
      - ./plex:/config:rw
      - /media/Torrents:/var/media/torrents:ro
      - /media/Movies:/var/media/movies:ro
      - /media/TV Shows:/var/media/tv:ro
