# get app names from `keyd-application-mapper -v`

# Find names with `keyd-application-mapper -v`
# Requires stopping keyd-application-mapper in KDE autostart GUI first
[*ghostty*]
# Undo ctrl-cmd swap in terminal
control = layer(control)
alt = layer(meta)

[steam-app*]
control = layer(control)
alt = layer(meta)
