[ids]
# Device info from `lsusb`
4355:0081 # CapsUnlocked

[aliases]
# Alias the keys to match the macbook keyboard. This lets the rest of the config
# be the same
leftalt = alias_of(leftmeta)
leftcontrol = alias_of(leftalt)

[main]
capslock = esc
meta = layer(control)
control = layer(meta)
