[ids]
05ac:0281:2bd1f3de

[main]
# Warning: this is broken right now. if you go back to linux on macbook,
# you'll need to add some aliases or something
capslock = esc
meta = layer(control)
control = layer(meta)
