endpoint: https://bitsight.atlassian.net
editor: vim
user: lucas.pickering@bitsighttech.com
authentication-method: api-token
password-source: keyring
project: RP
queries:
  me: |
    assignee = currentUser() AND resolution = unresolved AND (labels IS EMPTY OR labels NOT IN ("ignore", "opsgenie_alert")) ORDER BY status DESC, priority DESC, updated DESC
  vow: |
    assignee = currentUser() AND resolution = unresolved AND affectedVersion = "Onboarding Workflow" ORDER BY status DESC, priority DESC, updated DESC
  ignored: |
    assignee = currentUser() AND resolution = unresolved AND labels = "ignore" ORDER BY status DESC, priority DESC, updated DESC
custom-commands:
  - name: q
    help: Run a named query
    args:
      - name: NAME
        required: true
    script: |-
      {{jira}} ls -t list-table -n {{args.NAME}} -f priority,status,labels,versions,timetracking
  - name: go
    help: Open the ticket associated with the current git branch
    script: |-
      {{jira}} browse $(git rev-parse --abbrev-ref HEAD | grep -Eo '\bRP-\d+')
  - name: goc
    help: Open all tickets referenced by commits in the current git branch
    script: |-
      for issue in $(git cherry -v `git mbm` | grep -Eo '\bRP-\d+' | uniq); do
        {{jira}} browse $issue;
      done
  - name: commit
    help: Assign the proper committed label for this week to the given ticket
    args:
      - name: ISSUES
        required: true
        repeat: true
    script: |-
      d=$(date -dmonday +%Y%m%d)
      {{range args.ISSUES}}
        {{jira}} labels add {{.}} committed_${d}
      {{end}}
