endpoint: https://bitsight.atlassian.net
editor: vim
user: lucas.pickering@bitsighttech.com
authentication-method: api-token
password-source: keyring
project: RP
queries:
  me: |
    assignee = currentUser() AND resolution = unresolved AND type != Epic ORDER BY status DESC, priority DESC, updated DESC
  epics: |
    assignee = currentUser() AND resolution = unresolved AND type = Epic ORDER BY status DESC, priority DESC, updated DESC
  l2w: |
    assignee = currentUser() AND resolutiondate > startOfDay("-2w")
custom-commands:
  - name: q
    help: Run a named query
    args:
      - name: NAME
        required: true
    script: |-
      {{jira}} ls -t list-table -f priority,status,labels,versions,timetracking -n {{args.NAME}}

  - name: qq
    help: Run a query
    args:
      - name: QUERY
        required: true
    script: |-
      {{jira}} ls -t list-table -f priority,status,labels,versions,timetracking -q '{{args.QUERY}}'

  - name: go
    help: Open the ticket associated with the current git branch
    script: |-
      {{jira}} browse $(git rev-parse --abbrev-ref HEAD | grep -Eo '\b\w+-\d+')

  - name: goc
    help: Open all tickets referenced by commits in the current git branch
    script: |-
      for issue in $(git cherry -v `git mbm` | grep -Eo '\b\w+-\d+' | uniq); do
        {{jira}} browse $issue;
      done

  - name: blocks
    help: Mark one ticket as blocking another
    args:
      - name: BLOCKER
        required: true
      - name: BLOCKEE
        required: true
    script: |-
      {{jira}} issuelink {{args.BLOCKEE}} Blocks {{args.BLOCKER}}
