endpoint: https://rosintlabs.atlassian.net
editor: vim
user: lucas@keycaliber.com
authentication-method: api-token
password-source: keyring
project: KEYC
queries:
  me: |
    assignee = currentUser() AND resolution = unresolved AND type != "Story" ORDER BY status DESC, priority DESC, updated DESC
  milestones: |
    assignee = currentUser() AND resolution = unresolved AND type = "Story" ORDER BY status DESC, priority DESC, updated DESC
  l2w: |
    assignee = currentUser() AND resolutiondate > startOfDay("-2w")
custom-commands:
  - name: q
    help: Run a named query
    args:
      - name: NAME
        required: true
    script: |-
      {{jira}} ls -t list-table -f priority,status,labels,versions,timetracking -n {{args.NAME}}

  - name: qq
    help: Run a query
    args:
      - name: QUERY
        required: true
    script: |-
      {{jira}} ls -t list-table -f priority,status,labels,versions,timetracking -q '{{args.QUERY}}'

  - name: go
    help: Open the ticket associated with the current git branch
    script: |-
      {{jira}} browse $(git rev-parse --abbrev-ref HEAD | grep -Eo '\b\w+-\d+')

  - name: goc
    help: Open all tickets referenced by commits in the current git branch
    script: |-
      for issue in $(git cherry -v `git mbm` | grep -Eo '\b\w+-\d+' | uniq); do
        {{jira}} browse $issue;
      done

  - name: milestone
    help: Create a milestone under an epic
    args:
      - name: EPIC
        required: true
    script: |-
      ticket=$({{jira}} create -t milestone | cut -f2 -d' ')
      {{jira}} epic add {{args.EPIC}} $ticket

  - name: cc
    help: Clear remaining time and close
    args:
      - name: ISSUE
        required: true
    script: |-
      {{jira}} edit -o timetracking.remainingEstimate="0m" {{args.ISSUE}}
      # {{jira}} close --resolution=Fixed {{args.ISSUE}}

  - name: blocks
    help: Mark one ticket as blocking another
    args:
      - name: BLOCKER
        required: true
      - name: BLOCKEE
        required: true
    script: |-
      {{jira}} issuelink {{args.BLOCKEE}} Blocks {{args.BLOCKER}}
